<?php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            [1, 'الفاتحة', 'Al-Faatiha', 'The Opening', 7],
            [2, 'البقرة', 'Al-Baqarah', 'The Cow', 286],
            [3, 'آل عمران', 'Aal Imraan', 'The Family of Imran', 200],
            [4, 'النساء', 'An-Nisaa', 'The Women', 176],
            [5, 'المائدة', 'Al-Maaidah', 'The Table Spread', 120],
            [6, 'الأنعام', 'Al-An‘aam', 'The Cattle', 165],
            [7, 'الأعراف', 'Al-A‘raaf', 'The Heights', 206],
            [8, 'الأنفال', 'Al-Anfaal', 'The Spoils of War', 75],
            [9, 'التوبة', 'At-Tawbah', 'The Repentance', 129],
            [10, 'يونس', 'Yoonus', 'Jonah', 109],
            [11, 'هود', 'Huud', 'Hud', 123],
            [12, 'يوسف', 'Yuusuf', 'Joseph', 111],
            [13, 'الرعد', 'Ar-Ra‘d', 'The Thunder', 43],
            [14, 'إبراهيم', 'Ibraahiim', 'Abraham', 52],
            [15, 'الحجر', 'Al-Hijr', 'The Rocky Tract', 99],
            [16, 'النحل', 'An-Nahl', 'The Bee', 128],
            [17, 'الإسراء', 'Al-Israa', 'The Night Journey', 111],
            [18, 'الكهف', 'Al-Kahf', 'The Cave', 110],
            [19, 'مريم', 'Maryam', 'Mary', 98],
            [20, 'طه', 'Taa-Haa', 'Ta-Ha', 135],
            [21, 'الأنبياء', 'Al-Anbiyaa', 'The Prophets', 112],
            [22, 'الحج', 'Al-Hajj', 'The Pilgrimage', 78],
            [23, 'المؤمنون', 'Al-Mu’minuun', 'The Believers', 118],
            [24, 'النور', 'An-Nuur', 'The Light', 64],
            [25, 'الفرقان', 'Al-Furqaan', 'The Criterion', 77],
            [26, 'الشعراء', 'Ash-Shu‘araa', 'The Poets', 227],
            [27, 'النمل', 'An-Naml', 'The Ant', 93],
            [28, 'القصص', 'Al-Qasas', 'The Stories', 88],
            [29, 'العنكبوت', 'Al-Ankabuut', 'The Spider', 69],
            [30, 'الروم', 'Ar-Ruum', 'The Romans', 60],
            [31, 'لقمان', 'Luqmaan', 'Luqman', 34],
            [32, 'السجدة', 'As-Sajdah', 'The Prostration', 30],
            [33, 'الأحزاب', 'Al-Ahzaab', 'The Combined Forces', 73],
            [34, 'سبأ', 'Saba', 'Sheba', 54],
            [35, 'فاطر', 'Faatir', 'The Originator', 45],
            [36, 'يس', 'Yaa-Siin', 'Ya-Sin', 83],
            [37, 'الصافات', 'As-Saaffaat', 'Those Who Set The Ranks', 182],
            [38, 'ص', 'Saad', 'Sad', 88],
            [39, 'الزمر', 'Az-Zumar', 'The Troops', 75],
            [40, 'غافر', 'Ghaafir', 'The Forgiver', 85],
            [41, 'فصلت', 'Fussilat', 'Explained in Detail', 54],
            [42, 'الشورى', 'Ash-Shuuraa', 'The Consultation', 53],
            [43, 'الزخرف', 'Az-Zukhruf', 'The Ornaments of Gold', 89],
            [44, 'الدخان', 'Ad-Dukhaan', 'The Smoke', 59],
            [45, 'الجاثية', 'Al-Jaathiyah', 'The Crouching', 37],
            [46, 'الأحقاف', 'Al-Ahqaaf', 'The Wind-Curved Sandhills', 35],
            [47, 'محمد', 'Muhammad', 'Muhammad', 38],
            [48, 'الفتح', 'Al-Fath', 'The Victory', 29],
            [49, 'الحجرات', 'Al-Hujuraat', 'The Rooms', 18],
            [50, 'ق', 'Qaaf', 'Qaf', 45],
            [51, 'الذاريات', 'Adh-Dhaariyaat', 'The Winnowing Winds', 60],
            [52, 'الطور', 'At-Tuur', 'The Mount', 49],
            [53, 'النجم', 'An-Najm', 'The Star', 62],
            [54, 'القمر', 'Al-Qamar', 'The Moon', 55],
            [55, 'الرحمن', 'Ar-Rahmaan', 'The Beneficent', 78],
            [56, 'الواقعة', 'Al-Waaqi‘ah', 'The Inevitable', 96],
            [57, 'الحديد', 'Al-Hadiid', 'The Iron', 29],
            [58, 'المجادلة', 'Al-Mujaadila', 'The Pleading Woman', 22],
            [59, 'الحشر', 'Al-Hashr', 'The Exile', 24],
            [60, 'الممتحنة', 'Al-Mumtahanah', 'She That Is To Be Examined', 13],
            [61, 'الصف', 'As-Saff', 'The Ranks', 14],
            [62, 'الجمعة', 'Al-Jumu‘ah', 'The Congregation', 11],
            [63, 'المنافقون', 'Al-Munaafiquun', 'The Hypocrites', 11],
            [64, 'التغابن', 'At-Taghaabun', 'The Mutual Disillusion', 18],
            [65, 'الطلاق', 'At-Talaaq', 'The Divorce', 12],
            [66, 'التحريم', 'At-Tahrim', 'The Prohibition', 12],
            [67, 'الملك', 'Al-Mulk', 'The Sovereignty', 30],
            [68, 'القلم', 'Al-Qalam', 'The Pen', 52],
            [69, 'الحاقة', 'Al-Haaqqah', 'The Reality', 52],
            [70, 'المعارج', 'Al-Ma‘aarij', 'The Ascending Stairways', 44],
            [71, 'نوح', 'Nuuh', 'Noah', 28],
            [72, 'الجن', 'Al-Jinn', 'The Jinn', 28],
            [73, 'المزمل', 'Al-Muzzammil', 'The Enshrouded One', 20],
            [74, 'المدثر', 'Al-Muddaththir', 'The Cloaked One', 56],
            [75, 'القيامة', 'Al-Qiyaamah', 'The Resurrection', 40],
            [76, 'الإنسان', 'Al-Insaan', 'The Man', 31],
            [77, 'المرسلات', 'Al-Mursalaat', 'The Emissaries', 50],
            [78, 'النبأ', 'An-Naba', 'The Tidings', 40],
            [79, 'النازعات', 'An-Naazi‘aat', 'Those Who Drag Forth', 46],
            [80, 'عبس', 'Abasa', 'He Frowned', 42],
            [81, 'التكوير', 'At-Takwiir', 'The Overthrowing', 29],
            [82, 'الانفطار', 'Al-Infitaar', 'The Cleaving', 19],
            [83, 'المطففين', 'Al-Mutaffifiin', 'Defrauding', 36],
            [84, 'الانشقاق', 'Al-Inshiqaaq', 'The Sundering', 25],
            [85, 'البروج', 'Al-Buruuj', 'The Mansions of the Stars', 22],
            [86, 'الطارق', 'At-Taariq', 'The Morning Star', 17],
            [87, 'الأعلى', 'Al-A‘laa', 'The Most High', 19],
            [88, 'الغاشية', 'Al-Ghaashiyah', 'The Overwhelming', 26],
            [89, 'الفجر', 'Al-Fajr', 'The Dawn', 30],
            [90, 'البلد', 'Al-Balad', 'The City', 20],
            [91, 'الشمس', 'Ash-Shams', 'The Sun', 15],
            [92, 'الليل', 'Al-Layl', 'The Night', 21],
            [93, 'الضحى', 'Ad-Duhaa', 'The Morning Hours', 11],
            [94, 'الشرح', 'Ash-Sharh', 'The Relief', 8],
            [95, 'التين', 'At-Tiin', 'The Fig', 8],
            [96, 'العلق', 'Al-Alaq', 'The Clot', 19],
            [97, 'القدر', 'Al-Qadr', 'The Power', 5],
            [98, 'البينة', 'Al-Bayyinah', 'The Clear Proof', 8],
            [99, 'الزلزلة', 'Az-Zalzalah', 'The Earthquake', 8],
            [100, 'العاديات', 'Al-Aadiyaat', 'The Courser', 11],
            [101, 'القارعة', 'Al-Qaari‘ah', 'The Calamity', 11],
            [102, 'التكاثر', 'At-Takaathur', 'The Rivalry in World Increase', 8],
            [103, 'العصر', 'Al-Asr', 'The Declining Day', 3],
            [104, 'الهمزة', 'Al-Humazah', 'The Traducer', 9],
            [105, 'الفيل', 'Al-Fiil', 'The Elephant', 5],
            [106, 'قريش', 'Quraysh', 'Quraysh', 4],
            [107, 'الماعون', 'Al-Maa‘uun', 'The Small Kindnesses', 7],
            [108, 'الكوثر', 'Al-Kawthar', 'The Abundance', 3],
            [109, 'الكافرون', 'Al-Kaafiruun', 'The Disbelievers', 6],
            [110, 'النصر', 'An-Nasr', 'The Divine Support', 3],
            [111, 'المسد', 'Al-Masad', 'The Palm Fiber', 5],
            [112, 'الإخلاص', 'Al-Ikhlaas', 'The Sincerity', 4],
            [113, 'الفلق', 'Al-Falaq', 'The Daybreak', 5],
            [114, 'الناس', 'An-Naas', 'Mankind', 6],
        ];

        foreach ($surahs as [$number, $nameArabic, $nameSomali, $nameEnglish, $verseCount]) {
            Surah::query()->updateOrCreate(
                ['number' => $number],
                [
                    'name_arabic' => $nameArabic,
                    'name_somali' => $nameSomali,
                    'name_english' => $nameEnglish,
                    'verse_count' => $verseCount,
                ],
            );
        }
    }
}
